title: SnowDuck
description: Run Snowflake SQL locally, powered by DuckDB
baseurl: "/snowduck"
url: "https://hupe1980.github.io"

# Theme
remote_theme: just-the-docs/just-the-docs@v0.10.0
color_scheme: light

# Logo and favicon
logo: "/assets/logo.svg"
favicon_ico: "/assets/favicon.svg"

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation
nav_sort: case_insensitive
nav_external_links:
  - title: GitHub
    url: https://github.com/hupe1980/snowduck

# Footer
footer_content: "Copyright &copy; 2026 hupe1980. Distributed under the MIT License."

# Aux links
aux_links:
  "GitHub":
    - "https://github.com/hupe1980/snowduck"

aux_links_new_tab: true

# Heading anchor links
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Code copy button
enable_copy_code_button: true

# Callouts
callouts:
  warning:
    title: Warning
    color: yellow
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green

# Collections
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_exclude: false
      search_exclude: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
